/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinalmultplay;

import java.io.File;
import javax.print.attribute.standard.Media;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.stage.Stage;
import static javax.management.Query.attr;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josue
 */
public class Interfaz extends javax.swing.JFrame {
 private DefaultTableModel modeloTabla;
    private JTable tablaArchivos;
    private ReproductorMusica reproductorMusica;
    private JFXPanel jfxPanel; // Añadir JFXPanel
  private ReproductorVideo reproductorVideos;
  private GestionarArchivos gestionarArchivos;
  
  
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        setTitle("APPLE MUSIC");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocation(250,150); 
        initComponents();
        
        // Configuración del JFXPanel para reproducir videos
    JFXPanel videoPanel = new JFXPanel();
    reproductorVideo = new ReproductorVideo(videoPanel); // videoPanel es tu JFXPanel

    jPanel7.setLayout(new BorderLayout());
    jPanel7.add(videoPanel, BorderLayout.CENTER); // Añadir el JFXPanel al jPanel7
    
        reproductorMusica = new ReproductorMusica();
        // Configuración del JFXPanel
        jfxPanel = new JFXPanel(); // Inicializar JFXPanel
        add(jfxPanel, BorderLayout.SOUTH); // Añadir JFXPanel a la interfaz


    modeloTabla = new DefaultTableModel(new String[]{"NOMBRE", "ARCHIVO", "AUTOR", "ALBUM", "GENERO", "TAMAÑO", "RUTA"}, 0);
jTable.setModel(modeloTabla); // Asigna el modelo a la tabla
  // Inicializar la clase que gestiona los archivos
    gestionarArchivos = new GestionarArchivos(modeloTabla);
 
    jTable = new JTable(); // Inicializar jTable
     // Asignar el modelo a la tabla
    jTable.setModel(modeloTabla);
    jTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    // Añadir la tabla a un JScrollPane
        JScrollPane scrollPane = new JScrollPane(jTable);
        add(scrollPane, BorderLayout.CENTER); // Añadir JScrollPane a la interfaz
          
         // Añadir botón "Abrir Carpeta"
     
     // Iniciar JavaFX en el hilo correcto
        Platform.runLater(() -> {
            // Puedes inicializar cualquier cosa de JavaFX aquí si es necesario
        });
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        popupMenu1 = new java.awt.PopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        jMenu4 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        archivosBoton = new javax.swing.JButton();
        fotosBoton = new javax.swing.JButton();
        musicaBoton = new javax.swing.JButton();
        videosBoton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        botonBuscar = new javax.swing.JButton();
        borrarDuplicados = new javax.swing.JButton();
        play = new javax.swing.JButton();
        saltarmusica = new javax.swing.JButton();
        haciaAtrascancion = new javax.swing.JButton();
        verLetra = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Volumen = new javax.swing.JSlider();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        Abrircarpeta = new java.awt.Button();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        popupMenu1.setLabel("popupMenu1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        jMenu4.setText("jMenu4");

        popupMenu2.setLabel("popupMenu2");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setToolTipText("");
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        archivosBoton.setBackground(new java.awt.Color(51, 51, 51));
        archivosBoton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        archivosBoton.setForeground(new java.awt.Color(255, 255, 255));
        archivosBoton.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue\\OneDrive\\Documentos\\Proyecto 2\\Proyecto2\\src\\main\\java\\IMAGENES\\archivos NEGRO.png")); // NOI18N
        archivosBoton.setText("ARCHIVOS");
        archivosBoton.setBorderPainted(false);
        archivosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivosBotonActionPerformed(evt);
            }
        });

        fotosBoton.setBackground(new java.awt.Color(51, 51, 51));
        fotosBoton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fotosBoton.setForeground(new java.awt.Color(255, 255, 255));
        fotosBoton.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue\\OneDrive\\Documentos\\Proyecto 2\\Proyecto2\\src\\main\\java\\IMAGENES\\fotos negro.png")); // NOI18N
        fotosBoton.setText("      FOTOS");
        fotosBoton.setBorderPainted(false);
        fotosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotosBotonActionPerformed(evt);
            }
        });

        musicaBoton.setBackground(new java.awt.Color(51, 51, 51));
        musicaBoton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        musicaBoton.setForeground(new java.awt.Color(255, 255, 255));
        musicaBoton.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue\\OneDrive\\Documentos\\Proyecto 2\\Proyecto2\\src\\main\\java\\IMAGENES\\musica-de-manzana (1) NEGRO.png")); // NOI18N
        musicaBoton.setText("   MUSICA");
        musicaBoton.setBorderPainted(false);
        musicaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicaBotonActionPerformed(evt);
            }
        });

        videosBoton.setBackground(new java.awt.Color(51, 51, 51));
        videosBoton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        videosBoton.setForeground(new java.awt.Color(255, 255, 255));
        videosBoton.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue\\OneDrive\\Documentos\\Proyecto 2\\Proyecto2\\src\\main\\java\\IMAGENES\\clips (1) NEGRO.png")); // NOI18N
        videosBoton.setText("   VIDEOS");
        videosBoton.setBorderPainted(false);
        videosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videosBotonActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1252, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        botonBuscar.setBackground(new java.awt.Color(204, 204, 204));
        botonBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue\\OneDrive\\Documentos\\Proyecto 2\\Proyecto2\\src\\main\\java\\IMAGENES\\search.png")); // NOI18N
        botonBuscar.setBorderPainted(false);
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        borrarDuplicados.setBackground(new java.awt.Color(51, 51, 51));
        borrarDuplicados.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        borrarDuplicados.setForeground(new java.awt.Color(255, 255, 255));
        borrarDuplicados.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue\\OneDrive\\Desktop\\Proyecto\\delete.png")); // NOI18N
        borrarDuplicados.setText("Borrar Duplicados");
        borrarDuplicados.setBorderPainted(false);

        play.setBackground(new java.awt.Color(102, 102, 102));
        play.setForeground(new java.awt.Color(102, 102, 102));
        play.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue\\OneDrive\\Desktop\\Proyecto\\play.png")); // NOI18N
        play.setBorderPainted(false);
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        saltarmusica.setBackground(new java.awt.Color(102, 102, 102));
        saltarmusica.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue\\OneDrive\\Documentos\\Proyecto 2\\Proyecto2\\src\\main\\java\\IMAGENES\\fast-forward.png")); // NOI18N
        saltarmusica.setBorderPainted(false);
        saltarmusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saltarmusicaActionPerformed(evt);
            }
        });

        haciaAtrascancion.setBackground(new java.awt.Color(102, 102, 102));
        haciaAtrascancion.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue\\OneDrive\\Documentos\\Proyecto 2\\Proyecto2\\src\\main\\java\\IMAGENES\\backward.png")); // NOI18N
        haciaAtrascancion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        haciaAtrascancion.setBorderPainted(false);
        haciaAtrascancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haciaAtrascancionActionPerformed(evt);
            }
        });

        verLetra.setBackground(new java.awt.Color(102, 102, 102));
        verLetra.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue\\OneDrive\\Desktop\\Proyecto\\song-lyrics.png")); // NOI18N
        verLetra.setBorderPainted(false);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue\\OneDrive\\Desktop\\Proyecto\\add-playlist.png")); // NOI18N
        jButton1.setBorderPainted(false);

        Volumen.setBackground(new java.awt.Color(102, 102, 102));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue\\OneDrive\\Desktop\\Proyecto\\speaker.png")); // NOI18N
        jButton2.setBorderPainted(false);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue\\OneDrive\\Documentos\\Proyecto 2\\Proyecto2\\src\\main\\java\\IMAGENES\\repeat.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue\\OneDrive\\Documentos\\Proyecto 2\\Proyecto2\\src\\main\\java\\IMAGENES\\voice.png")); // NOI18N

        jTable.setAutoCreateRowSorter(true);
        jTable.setBackground(new java.awt.Color(51, 51, 51));
        jTable.setForeground(new java.awt.Color(255, 255, 255));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NOMBRE", "ARCHIVO", "AUTOR", "ALBUM", "GENERO", "TAMAÑO", "RUTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTable);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        Abrircarpeta.setBackground(new java.awt.Color(153, 153, 153));
        Abrircarpeta.setLabel("Abrir Carpeta");
        Abrircarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrircarpetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(haciaAtrascancion)
                                        .addGap(45, 45, 45)
                                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(saltarmusica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(verLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Volumen, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(409, 409, 409))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonBuscar)
                                        .addGap(20, 20, 20)
                                        .addComponent(Abrircarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(borrarDuplicados)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(musicaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(videosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(fotosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(archivosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(805, 805, 805)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Abrircarpeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(archivosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fotosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(musicaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(videosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(borrarDuplicados)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(saltarmusica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(play, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(haciaAtrascancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(verLetra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(Volumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 983, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   // Método para reproducir música usando JavaFX
private ReproductorVideo reproductorVideo;


    private void haciaAtrascancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haciaAtrascancionActionPerformed
        // Detener la reproducción actual
    reproductorMusica.detenerMusica();   
// Obtener la fila seleccionada
    int filaSeleccionada = jTable.getSelectedRow();
    
    // Si no hay una selección, reproducimos desde la última canción
    if (filaSeleccionada == -1 || filaSeleccionada == 0) {
        filaSeleccionada = modeloTabla.getRowCount() - 1; // Ir a la última fila si estamos en la primera o no hay selección
    } else {
        filaSeleccionada--; // Mover hacia la canción anterior
    }
    
    // Seleccionar la fila en la tabla
    jTable.setRowSelectionInterval(filaSeleccionada, filaSeleccionada);
    
    // Obtener la ruta del archivo de la fila seleccionada
    String rutaArchivo = (String) modeloTabla.getValueAt(filaSeleccionada, 6);
    String extension = gestionarArchivos.getFileExtension(new File(rutaArchivo)).toLowerCase();
    
    // Verificar si es un archivo de audio o video
    if (extension.equals("mp3") || extension.equals("wav") || extension.equals("flac")) {
        reproductorMusica.reproducirMusica(rutaArchivo); // Reproducir la música
    } else if (extension.equals("mp4") || extension.equals("avi") || extension.equals("mkv")) {
        playVideoInPanel(rutaArchivo); // Reproducir el video
    } else {
        JOptionPane.showMessageDialog(this, "Formato no soportado.");
    }
    }//GEN-LAST:event_haciaAtrascancionActionPerformed

    private void saltarmusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saltarmusicaActionPerformed
           // Detener la reproducción actual
    reproductorMusica.detenerMusica();
// Obtener la fila seleccionada
    int filaSeleccionada = jTable.getSelectedRow();
    
    // Si no hay una selección, reproducimos desde la primera canción
    if (filaSeleccionada == -1 || filaSeleccionada == modeloTabla.getRowCount() - 1) {
        filaSeleccionada = 0; // Ir a la primera fila si estamos en la última o no hay selección
    } else {
        filaSeleccionada++; // Mover hacia la canción siguiente
    }
    
    // Seleccionar la fila en la tabla
    jTable.setRowSelectionInterval(filaSeleccionada, filaSeleccionada);
    
    // Obtener la ruta del archivo de la fila seleccionada
    String rutaArchivo = (String) modeloTabla.getValueAt(filaSeleccionada, 6);
    String extension = gestionarArchivos.getFileExtension(new File(rutaArchivo)).toLowerCase();
    
    // Verificar si es un archivo de audio o video
    if (extension.equals("mp3") || extension.equals("wav") || extension.equals("flac")) {
        reproductorMusica.reproducirMusica(rutaArchivo); // Reproducir la música
    } else if (extension.equals("mp4") || extension.equals("avi") || extension.equals("mkv")) {
        playVideoInPanel(rutaArchivo); // Reproducir el video
    } else {
        JOptionPane.showMessageDialog(this, "Formato no soportado.");
    }
    }//GEN-LAST:event_saltarmusicaActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
 int filaSeleccionada = jTable.getSelectedRow();

    // si no se selecciona nada que reproduzca la primera de la lista
    if (filaSeleccionada == -1) {
        filaSeleccionada = 0; //selecion de la primera
        jTable.setRowSelectionInterval(0, 0); // Marca visualmente la selección en la tabla
    }

    // Asegúrate de que haya al menos una fila en la tabla antes de intentar reproducir
    if (modeloTabla.getRowCount() > 0) {
        // Obtener la ruta del archivo de la fila seleccionada
        String rutaArchivo = (String) modeloTabla.getValueAt(filaSeleccionada, 6);
        String extension = gestionarArchivos.getFileExtension(new File(rutaArchivo)).toLowerCase();

        // Verificar si es un archivo de audio o video
        if (extension.equals("mp3") || extension.equals("wav") || extension.equals("flac")) {
            reproductorMusica.reproducirMusica(rutaArchivo); // Reproducir música
        } else if (extension.equals("mp4") || extension.equals("avi") || extension.equals("mkv")) {
            playVideoInPanel(rutaArchivo); // Reproducir video
        } else {
            JOptionPane.showMessageDialog(this, "Formato no soportado.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "No hay archivos para reproducir.");
    }
    }//GEN-LAST:event_playActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
          // Obtener la ruta ingresada en el jTextField1
        String rutaCarpeta = jTextField1.getText();

        // Crear un objeto File con la ruta ingresada
        File carpeta = new File(rutaCarpeta);

        // Verificar si la ruta es valida
        if (carpeta.exists() && carpeta.isDirectory()) {
            gestionarArchivos.listarArchivosEnCarpeta(carpeta);
        } else {
            JOptionPane.showMessageDialog(this, "La ruta ingresada no es válida o no es una carpeta.");
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void videosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videosBotonActionPerformed
    String rutaCarpeta = jTextField1.getText();
    File carpeta = new File(rutaCarpeta);
    
    if (carpeta.exists() && carpeta.isDirectory()) {
        gestionarArchivos.filtrarArchivosEnCarpeta(carpeta,"videos"); // Filtrar para mostrar solo videos
    } else {
        JOptionPane.showMessageDialog(this, "La ruta ingresada no es válida o no es una carpeta.");
    }
    }//GEN-LAST:event_videosBotonActionPerformed

    private void musicaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicaBotonActionPerformed
        String rutaCarpeta = jTextField1.getText();
    File carpeta = new File(rutaCarpeta);
    
    if (carpeta.exists() && carpeta.isDirectory()) {
        gestionarArchivos.filtrarArchivosEnCarpeta(carpeta, "musica"); // Filtrar para mostrar solo música
    } else {
        JOptionPane.showMessageDialog(this, "La ruta ingresada no es valida o no es una carpeta.");
    }
    }//GEN-LAST:event_musicaBotonActionPerformed

    private void fotosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotosBotonActionPerformed
       String rutaCarpeta = jTextField1.getText();
    File carpeta = new File(rutaCarpeta);
    
    if (carpeta.exists() && carpeta.isDirectory()) {
        gestionarArchivos.filtrarArchivosEnCarpeta(carpeta,"fotos"); // Filtrar para mostrar solo fotos
    } else {
        JOptionPane.showMessageDialog(this, "La ruta ingresada no es valida o no es una carpeta.");
    }
    }//GEN-LAST:event_fotosBotonActionPerformed

    private void archivosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivosBotonActionPerformed
         String rutaCarpeta = jTextField1.getText();
    File carpeta = new File(rutaCarpeta);
    
    if (carpeta.exists() && carpeta.isDirectory()) {
        gestionarArchivos.filtrarArchivosEnCarpeta(carpeta,"todos"); // Filtrar para mostrar todos los archivos
    } else {
        JOptionPane.showMessageDialog(this, "La ruta ingresada no es valida o no es una carpeta.");
    }
    }//GEN-LAST:event_archivosBotonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void AbrircarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrircarpetaActionPerformed
// Crear un JFileChooser para seleccionar carpetas
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

    int returnValue = fileChooser.showOpenDialog(this);
    if (returnValue == JFileChooser.APPROVE_OPTION) {
        File carpetaSeleccionada = fileChooser.getSelectedFile();

        // Verificar si es un directorio válido
        if (carpetaSeleccionada.isDirectory()) {
            // Listar archivos en la carpeta seleccionada
            gestionarArchivos.listarArchivosEnCarpeta(carpetaSeleccionada);
        } else {
            JOptionPane.showMessageDialog(this, "La ruta seleccionada no es una carpeta válida.");
        }
    }
    }//GEN-LAST:event_AbrircarpetaActionPerformed
     private String obtenerAutor(File archivo) {
    // Implementa la lógica para obtener el autor si es un archivo multimedia
    return ""; // Si no aplica, retorna un string vacío
}

private String obtenerAlbum(File archivo) {
    // Implementa la lógica para obtener el álbum
    return "";
}

private String obtenerGenero(File archivo) {
    // Implementa la lógica para obtener el género
    return "";
}
 // Método para reproducir video en jPanel7 usando la clase ReproductorVideo
    private void playVideoInPanel(String rutaArchivo) {
      reproductorVideo.reproducirVideo(rutaArchivo); // Llamar al método para reproducir el video
    }
private void listarArchivosDesdeInterfaz() {
    gestionarArchivos.listarArchivos();
}

public void filtrarArchivosDesdeInterfaz(String tipo) {
    gestionarArchivos.filtrarArchivos(tipo);
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Abrircarpeta;
    private javax.swing.JSlider Volumen;
    private javax.swing.JButton archivosBoton;
    private javax.swing.JButton borrarDuplicados;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton fotosBoton;
    private javax.swing.JButton haciaAtrascancion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private javax.swing.JButton musicaBoton;
    private javax.swing.JButton play;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JButton saltarmusica;
    private javax.swing.JButton verLetra;
    private javax.swing.JButton videosBoton;
    // End of variables declaration//GEN-END:variables

    void start(Stage stage) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
